name: Android CI/CD

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  pr-checks:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    concurrency:
      group: pr-${{ github.head_ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Detekt (non-blocking)
        run: ./gradlew detekt || echo "::warning file=detekt::Detekt found issues, but will not fail the build"

      - name: Build (blocking)
        run: ./gradlew build

      - name: Run Unit Tests (blocking)
        run: ./gradlew test

  release-on-main:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build
        run: ./gradlew build

      - name: Validate version number
        id: version_check
        run: |
          VERSION_NAME=$(grep versionName app/build.gradle | head -1 | sed 's/.*"\(.*\)".*/\1/')
          TAG_EXISTS=$(git tag -l "v$VERSION_NAME")
          if [ ! -z "$TAG_EXISTS" ]; then
            echo "Version $VERSION_NAME already exists as a tag. Please bump the version before deploying."
            exit 1
          fi
          echo "version_name=$VERSION_NAME" >> $GITHUB_OUTPUT

      - name: Assemble Release APK
        run: ./gradlew assembleRelease

      - name: Create Release and Tag
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version_check.outputs.version_name }}
          name: Release v${{ steps.version_check.outputs.version_name }}
          files: app/build/outputs/apk/release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}